""" version which can be consumed from within the module """
VERSION_STR = "0.0.7"
DESCRIPTION = "module to help you maintain third party apt repos in a sane way"
APP_NAME = "pyapt"
LOGGER_NAME = "pyapt"
